/* SPDX-License-Identifier: GPL-3.0-or-later */
/*
 * gpu_xenos.c - the 360 side of the PSX libgpu, replacing gpu_nv2a.c.
 *
 * gpu_xbox.c owns the hardware-agnostic half of the renderer (ordering-table
 * walk, PSX primitive decode, screen transform) and compiles for PPC unchanged.
 * This file is only the hardware end: batch the vertices it produces, map PSX
 * draw state onto Xenos state, and submit.
 *
 * SHADERS ARE EMBEDDED (shaders_embedded.c), compiled from the HLSL in shaders/ with
 * the Xbox 360 XDK's fxc. They were an on-disk asset first, for flexibility;
 * that cost two hardware test runs to "shaders not found" for a pair of blobs
 * under a kilobyte combined, which is a bad trade. A vs.vsu / ps.psu beside the
 * disc image still OVERRIDES the embedded pair, so iterating on shaders does not
 * need an ELF rebuild -- the flexibility is kept, the failure mode is not.
 *
 * A file named "nogpu" beside the disc image keeps Xe down entirely. That
 * matters because Xe_Init takes the framebuffer that libXenon's console draws
 * into in software, so once the GPU is up the on-screen boot text is gone;
 * getting it back should not require a different build.
 */
#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include <xenos/xe.h>
#include <xenos/xenos.h>
#include <console/console.h>

#include "gpu_nv2a.h"
#include "sh_log.h"
#include "sh_hwperf.h"
#include "fs_xbox360.h"

/* Baked-in shaders (shaders_embedded.c, generated by tools/embed_shaders.py).
 * Deliberately not const: Xe patches the vertex-fetch instructions in place. */
extern unsigned char      g_ShaderVsEmbedded[];
extern const unsigned int g_ShaderVsEmbedded_len;
extern unsigned char      g_ShaderPsEmbedded[];
extern const unsigned int g_ShaderPsEmbedded_len;

static void ApplyBlendState(void);
static void ApplyRenderState(void);
static void FlushBatch(void);

/* --- device ---------------------------------------------------------------- */

static struct XenosDevice  s_xeDev;
static struct XenosDevice* s_xe;                 /* NULL until Init succeeds */
static struct XenosSurface* s_fb;
static struct XenosShader*  s_vs;
static struct XenosShader*  s_ps;
static int                  s_ready;             /* device AND shaders up */
static int                  s_warned;

/* --- per-frame counters ---------------------------------------------------- */

static unsigned s_frame;
static unsigned s_batchVertsThisFrame;
static unsigned s_batchCalls;
static unsigned s_drawsThisFrame;
static unsigned s_texBindsThisFrame;
static unsigned s_blendChanges;
static unsigned s_scissorChanges;

/* --- vertex staging -------------------------------------------------------- */

/* gpu_xbox.c reserves vertices through BatchAlloc and writes them in place, so
 * this must be real writable memory at the ShVertex stride whether or not a GPU
 * is behind it. Batches are flushed on any state change and at frame end, which
 * is what keeps draw order correct -- the PSX ordering table is painter-order,
 * so a primitive drawn under the wrong blend or texture is not merely wrong, it
 * is wrong in a way that looks like a depth bug. */
#define GPU_POOL_VERTS 32768
static ShVertex s_pool[GPU_POOL_VERTS];
static int      s_poolUsed;
static int      s_flushStart;                    /* first unsubmitted vertex */

/* --- PSX draw state (mirrored, applied at flush) --------------------------- */

static const void* s_texAddr;
static int         s_texW, s_texH;
static int         s_blendMode;                  /* 0 = opaque, 1..4 = PSX ABR */
static int         s_scX, s_scY, s_scW, s_scH;

/* psx_vram hands us a plain ARGB8888 CPU buffer, not a GPU surface, so the
 * pixels have to be copied into one. A single scratch texture is reused for
 * every bind: PSX pages are at most 256x256 and batches flush on each bind, so
 * the previous contents are already drawn by the time it is overwritten. */
#define GPU_TEX_MAX 256
static struct XenosSurface* s_tex;
static struct XenosSurface* s_white;             /* 1x1 opaque, for untextured prims */
static struct XenosSurface* s_curTex;
static float                s_texScale[4] = { 1.0f, 1.0f, 0.0f, 0.0f };

int                g_Nv2aFrameCount;
int                g_Nv2aContentX = 0;
int                g_Nv2aContentW = 640;
int                g_Nv2aContentH = 480;
unsigned long long g_Nv2aDrawCycles;

/* ShVertex is pos[4], col[4], tex[2], spec[4], pad[2] -- 64 bytes.
 *
 * The vertex STRIDE is NOT taken from Xe_SetStreamSource (that parameter is
 * ignored -- see the call site). It is Xe_VBFCalcStride of this table, i.e. the
 * sum of the element sizes, baked into the shader by
 * Xe_ShaderApplyVFetchPatches. So this table must describe all SIXTY-FOUR bytes:
 * the four real attributes only add up to 56, and an under-declared stride does
 * not fail loudly -- it walks each successive vertex 8 bytes further off the
 * rails, which looks like corrupt geometry rather than a format error.
 *
 * The trailing pad exists for NV2A write-combining and carries nothing, so it is
 * declared as an unreferenced texcoord purely to make the arithmetic come out. */
static const struct XenosVBFFormat s_vbf = {
    5,
    {
        { XE_USAGE_POSITION, 0, XE_TYPE_FLOAT4 },   /* 16 : screen x,y,z,w     */
        { XE_USAGE_NORMAL,   0, XE_TYPE_FLOAT4 },   /* 16 : diffuse colour     */
        { XE_USAGE_TEXCOORD, 0, XE_TYPE_FLOAT2 },   /*  8 : texel u,v          */
        { XE_USAGE_TEXCOORD, 1, XE_TYPE_FLOAT4 },   /* 16 : fog / specular     */
        { XE_USAGE_TEXCOORD, 2, XE_TYPE_FLOAT2 },   /*  8 : pad -> 64 total    */
    }
};

static void* LoadFile(const char* path, int* sizeOut)
{
    FILE* f = fopen(path, "rb");
    long  n;
    void* buf;

    if (!f)
        return NULL;
    fseek(f, 0, SEEK_END);
    n = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (n <= 0) { fclose(f); return NULL; }

    buf = memalign(128, (size_t)n);
    if (!buf) { fclose(f); return NULL; }
    if (fread(buf, 1, (size_t)n, f) != (size_t)n) { free(buf); fclose(f); return NULL; }
    fclose(f);
    if (sizeOut) *sizeOut = (int)n;
    return buf;
}

/* Where the shaders were actually found, so LoadShaders does not have to repeat
 * the search and the log can name the exact directory. */
static char s_shaderDir[SH360_PATH_MAX * 2];

static int FileExists(const char* path)
{
    FILE* f = fopen(path, "rb");
    if (!f)
        return 0;
    fclose(f);
    return 1;
}

/* An on-disk pair OVERRIDES the embedded shaders, so iterating on them does not
 * need an ELF rebuild. Absent, the embedded copies are used and the renderer
 * comes up regardless -- which is the point: two hardware runs were spent on
 * "shaders not found" when the blobs are under a kilobyte combined. */
static int ShadersOnDisk(void)
{
    /* Beside the disc image first, then the volume root. */
    static const char* const kDirs[2] = { NULL, "uda:/" };
    char  vs[SH360_PATH_MAX * 2], ps[SH360_PATH_MAX * 2];
    int   i;

    for (i = 0; i < 2; i++) {
        const char* dir = kDirs[i] ? kDirs[i] : Sh360Fs_DataRoot();
        snprintf(vs, sizeof(vs), "%svs.vsu", dir);
        snprintf(ps, sizeof(ps), "%sps.psu", dir);
        if (FileExists(vs) && FileExists(ps)) {
            snprintf(s_shaderDir, sizeof(s_shaderDir), "%s", dir);
            SH_DBG("[GPU] using OVERRIDE shaders from '%s'", s_shaderDir);
            return 1;
        }
    }
    s_shaderDir[0] = '\0';
    return 0;
}

/* Escape hatch: a file named "nogpu" beside the disc image keeps Xe down, which
 * hands the framebuffer back to libXenon's software console. Worth having --
 * once the GPU owns the screen, the on-screen boot text is gone, and getting it
 * back should not require a different build. */
static int GpuDisabledByFile(void)
{
    char path[SH360_PATH_MAX * 2];
    snprintf(path, sizeof(path), "%snogpu", Sh360Fs_DataRoot());
    if (!FileExists(path))
        return 0;
    SH_DBG("[GPU] '%s' present - leaving Xe down, console stays readable", path);
    return 1;
}

static int LoadShaders(void)
{
    char  path[SH360_PATH_MAX * 4];
    /* MUST be initialised. Left uninitialised, the "no override present" path
     * fell straight into `if (!vsBlob || !psBlob)` with stack garbage, which was
     * non-NULL, so the embedded fallback was SKIPPED and the magic check read
     * random memory (hardware log 028: "shader magic bad: vs=9ddf ps=8143").
     * The gate compiles at -O0, where gcc's -Wmaybe-uninitialised analysis does
     * not run, so nothing warned. */
    void* vsBlob = NULL;
    void* psBlob = NULL;

    if (s_shaderDir[0]) {
        snprintf(path, sizeof(path), "%svs.vsu", s_shaderDir);
        vsBlob = LoadFile(path, NULL);
        snprintf(path, sizeof(path), "%sps.psu", s_shaderDir);
        psBlob = LoadFile(path, NULL);
        if (!vsBlob || !psBlob) {
            SH_DBG("[GPU] override shaders failed to read - falling back to embedded");
            vsBlob = psBlob = NULL;
        }
    }
    if (!vsBlob || !psBlob) {
        /* Xe keeps these pointers and patches the blobs in place, so they must
         * stay writable and alive for the shader's lifetime -- which a .data
         * array is, and a freed heap copy would not be. */
        vsBlob = g_ShaderVsEmbedded;
        psBlob = g_ShaderPsEmbedded;
        SH_DBG("[GPU] using embedded shaders (vs=%u ps=%u bytes)",
               g_ShaderVsEmbedded_len, g_ShaderPsEmbedded_len);
    }

    /* libXenon does not RETURN an error for a bad blob -- Xe_LoadShaderFromMemory
     * calls Xe_Fatal, which never comes back. Check the magic ourselves so a
     * wrong or truncated file is a log line rather than a silent lockup. */
    {
        const unsigned char* v = (const unsigned char*)vsBlob;
        const unsigned char* p = (const unsigned char*)psBlob;
        if (v[0] != 0x10 || v[1] != 0x2a || p[0] != 0x10 || p[1] != 0x2a) {
            SH_DBG("[GPU] shader magic bad: vs=%02x%02x ps=%02x%02x (want 102a) - not loading",
                   v[0], v[1], p[0], p[1]);
            return 0;
        }
    }

    s_ps = Xe_LoadShaderFromMemory(s_xe, psBlob);
    s_vs = Xe_LoadShaderFromMemory(s_xe, vsBlob);
    if (!s_ps || !s_vs) {
        SH_DBG("[GPU] shader load FAILED (vs=%p ps=%p)", (void*)s_vs, (void*)s_ps);
        return 0;
    }
    Xe_InstantiateShader(s_xe, s_ps, 0);
    Xe_InstantiateShader(s_xe, s_vs, 0);
    /* Patches the vertex-fetch instructions to match our layout, which is why
     * the shader's declared input order does not have to match ours. */
    Xe_ShaderApplyVFetchPatches(s_xe, s_vs, 0, &s_vbf);
    SH_DBG("[GPU] shaders loaded and instantiated");
    return 1;
}

void GpuNv2a_Init(void)
{
    s_frame = 0;
    s_scX = s_scY = 0;
    s_scW = g_Nv2aContentW;
    s_scH = g_Nv2aContentH;

    /* Decided BEFORE touching Xe: Xe_Init takes ownership of the framebuffer,
     * which is the surface libXenon's console draws into in software, so once it
     * is up the on-screen boot text is gone for good. */
    if (GpuDisabledByFile()) {
        s_xe = NULL;
        return;
    }
    ShadersOnDisk();   /* records an override directory, or clears it */

    s_xe = &s_xeDev;
    memset(s_xe, 0, sizeof(*s_xe));
    Xe_Init(s_xe);

    s_fb = Xe_GetFramebufferSurface(s_xe);
    if (!s_fb) {
        SH_DBG("[GPU] Xe_GetFramebufferSurface returned NULL - count-only mode");
        s_xe = NULL;
        return;
    }
    Xe_SetRenderTarget(s_xe, s_fb);
    SH_DBG("[GPU] Xe up: framebuffer %dx%d", s_fb->width, s_fb->height);

    s_ready = LoadShaders();
    if (!s_ready) {
        SH_DBG("[GPU] shaders present but failed to load - count-only mode");
        return;
    }

    s_tex   = Xe_CreateTexture(s_xe, GPU_TEX_MAX, GPU_TEX_MAX, 1,
                               XE_FMT_8888 | XE_FMT_ARGB, 0);
    s_white = Xe_CreateTexture(s_xe, 1, 1, 1, XE_FMT_8888 | XE_FMT_ARGB, 0);
    if (!s_tex || !s_white) {
        SH_DBG("[GPU] texture creation FAILED (tex=%p white=%p)",
               (void*)s_tex, (void*)s_white);
        s_ready = 0;
        return;
    }
    {   /* Untextured primitives sample this instead of whatever happened to be
         * bound, so their vertex colour comes through unmodified. */
        unsigned* px = (unsigned*)Xe_Surface_LockRect(s_xe, s_white, 0, 0, 1, 1, XE_LOCK_WRITE);
        if (px)
            px[0] = 0xFFFFFFFFu;
        Xe_Surface_Unlock(s_xe, s_white);
    }
    s_curTex = s_white;

    /* Depth comes from the ordering table (painter order), not a Z test. */
    Xe_SetZEnable(s_xe, 0);
    Xe_SetZWrite(s_xe, 0);
    Xe_SetCullMode(s_xe, XE_CULL_NONE);
    SH_DBG("[GPU] textures ready, renderer ARMED");
    SH_DBG("[GPU] xenos backend: %d-vertex pool, %d B/vertex",
           GPU_POOL_VERTS, (int)sizeof(ShVertex));
}

/* Submit whatever has accumulated since the last flush under the CURRENT state.
 * Called before every state change so the batch that was built under the old
 * state is the batch that gets drawn with it. */
static void FlushBatch(void)
{
    int count = s_poolUsed - s_flushStart;
    struct XenosVertexBuffer* vb;
    void* dst;

    if (count <= 0)
        return;
    if (!s_ready) {                 /* count-only mode: account and drop */
        s_flushStart = s_poolUsed;
        return;
    }

    vb = Xe_CreateVertexBuffer(s_xe, count * (int)sizeof(ShVertex));
    if (!vb) {
        SH_DBG("[GPU] Xe_CreateVertexBuffer(%d verts) failed", count);
        s_flushStart = s_poolUsed;
        return;
    }
    dst = Xe_VB_Lock(s_xe, vb, 0, count * (int)sizeof(ShVertex), XE_LOCK_WRITE);
    if (dst) {
        memcpy(dst, &s_pool[s_flushStart], (size_t)count * sizeof(ShVertex));
        Xe_VB_Unlock(s_xe, vb);

        {   /* Screen pixels -> clip space. Y is negated because PSX screen Y
             * grows downward. Recomputed per flush so a scissor/content-rect
             * change cannot leave a stale mapping behind. */
            float vp[4];
            vp[0] =  2.0f / (float)g_Nv2aContentW;
            vp[1] = -2.0f / (float)g_Nv2aContentH;
            vp[2] = -1.0f;
            vp[3] =  1.0f;
            Xe_SetVertexShaderConstantF(s_xe, 0, vp, 1);
            Xe_SetVertexShaderConstantF(s_xe, 1, s_texScale, 1);

            /* Output alpha = texel.a * x + y. ABR0 on a TEXTURED primitive must
             * use the texel's own alpha, because psx_vram encodes the PSX STP
             * bit as 0x80 vs 0xFF and that reproduces per-texel semi-
             * transparency exactly. Untextured has no such alpha (white is 1.0),
             * so the weight comes from the constant instead. */
            {
                float blend[4] = { 0.0f, 1.0f, 0.0f, 0.0f };
                int   textured = (s_curTex && s_curTex != s_white);
                if (s_blendMode == 1) {
                    if (textured) { blend[0] = 1.0f;  blend[1] = 0.0f;  }
                    else          { blend[0] = 0.0f;  blend[1] = 0.5f;  }
                } else if (s_blendMode == 4) {
                    blend[0] = 0.0f; blend[1] = 0.25f;
                }
                Xe_SetPixelShaderConstantF(s_xe, 0, blend, 1);
            }
        }
        Xe_SetShader(s_xe, SHADER_TYPE_PIXEL,  s_ps, 0);
        Xe_SetShader(s_xe, SHADER_TYPE_VERTEX, s_vs, 0);
        /* The stride argument is IGNORED by libXenon (Xe_SetStreamSource never
         * reads it); the real stride is baked into the shader from s_vbf by
         * Xe_ShaderApplyVFetchPatches. Passed for documentation only. */
        Xe_SetStreamSource(s_xe, 0, vb, 0, (int)sizeof(ShVertex));
        Xe_SetTexture(s_xe, 0, s_curTex ? s_curTex : s_white);
        Xe_DrawPrimitive(s_xe, XE_PRIMTYPE_TRIANGLELIST, 0, count / 3);
        s_drawsThisFrame++;
    }
    /* Returned to the pool rather than freed: the GPU may still be reading it,
     * and the pool defers reuse until the frame has drained. */
    Xe_VBPoolAdd(s_xe, vb);
    s_flushStart = s_poolUsed;
}

void GpuNv2a_FrameBegin(void)
{
    /* Doubles as psx_vram.c's texture-cache LRU clock, so it has to tick even
     * with no rendering behind it or every cached page looks equally stale. */
    g_Nv2aFrameCount++;
    s_poolUsed            = 0;
    s_flushStart          = 0;
    s_batchVertsThisFrame = 0;
    s_batchCalls          = 0;
    s_drawsThisFrame      = 0;
    s_texBindsThisFrame   = 0;
    s_blendChanges        = 0;
    s_scissorChanges      = 0;

    if (s_xe) {
        Xe_InvalidateState(s_xe);
        Xe_SetClearColor(s_xe, GpuXbox_GetClearColor());
        /* Re-assert everything AFTER the invalidate. The Set* entry points below
         * early-return when their cached value is unchanged, so without this the
         * per-frame invalidate could drop state that the game never sets again
         * -- most of the time the blend mode and scissor do not change between
         * frames, which is exactly when it would go missing. */
        ApplyRenderState();
    }
}

void GpuNv2a_FrameEnd(void)
{
    FlushBatch();

    if (s_xe) {
        Xe_Resolve(s_xe);            /* EDRAM tile -> framebuffer */
        Xe_Sync(s_xe);
    }

    if ((s_frame % 60) == 0) {
        /* verts/prims come from BatchAlloc, which is the path gpu_xbox.c
         * actually uses. An earlier version counted triangles in EmitTris --
         * which NOTHING calls -- so it read a constant zero and looked like a
         * rendering failure when it was a dead counter. */
        SH_DBG("[GPU] frame=%u prims=%u verts=%u draws=%u texbind=%u blend=%u scissor=%u ready=%d",
               s_frame, s_batchCalls, s_batchVertsThisFrame, s_drawsThisFrame,
               s_texBindsThisFrame, s_blendChanges, s_scissorChanges, s_ready);
    }
    s_frame++;
}

void GpuNv2a_WaitVbl(void)
{
    /* Xe_Sync in FrameEnd already blocks until the GPU drains once a device is
     * up. Without one there is nothing to block on, and returning immediately
     * let the loop free-run to TEN MILLION frames in a session, which makes
     * every timing-dependent behaviour in the log meaningless. */
    static unsigned long long s_next;
    const unsigned long long  period = PPC_TIMEBASE_FREQ / 60;
    unsigned long long        now    = mftb();

    /* Resync rather than sprint to catch up: a blocking CD load stalls the loop
     * for many frames, and replaying them at full speed is worse than dropping. */
    if (s_next == 0 || now > s_next + period * 8)
        s_next = now;

    s_next += period;
    while (mftb() < s_next) { }
}

void GpuNv2a_EmitTris(const ShVertex* verts, int count)
{
    /* gpu_xbox.c does not use this path -- it writes through BatchAlloc -- but
     * the entry point is part of the interface, so honour it rather than
     * silently dropping geometry if a caller ever appears. */
    ShVertex* d;
    if (!verts || count <= 0)
        return;
    d = GpuNv2a_BatchAlloc(count);
    if (d)
        memcpy(d, verts, (size_t)count * sizeof(ShVertex));
}

ShVertex* GpuNv2a_BatchAlloc(int count)
{
    ShVertex* p;

    if (count <= 0 || count > GPU_POOL_VERTS)
        return NULL;
    if (s_poolUsed + count > GPU_POOL_VERTS) {
        FlushBatch();               /* submit what we have, then reuse the pool */
        s_poolUsed = s_flushStart = 0;
    }

    p = &s_pool[s_poolUsed];
    s_poolUsed += count;
    s_batchVertsThisFrame += (unsigned)count;
    s_batchCalls++;
    return p;
}

void GpuNv2a_BindPaletted(const void* page, const void* palette)
{
    (void)page; (void)palette;
    /* The paletted path decodes through psx_vram's cache before reaching us, so
     * there is nothing to bind separately until that cache hands over a
     * XenosSurface. Counted so the log still shows the path is exercised. */
    s_texBindsThisFrame++;
}

void GpuNv2a_BindTexture(const void* addr, int w, int h)
{
    if (addr == s_texAddr && w == s_texW && h == s_texH)
        return;                     /* redundant bind: do not break the batch */
    FlushBatch();
    s_texAddr = addr;
    s_texW = w;
    s_texH = h;
    s_texBindsThisFrame++;

    if (!s_ready || !addr || w <= 0 || h <= 0) {
        s_curTex = s_white;
        return;
    }
    if (w > GPU_TEX_MAX || h > GPU_TEX_MAX) {
        /* Never silently sample a wrong-sized page: fall back to white so the
         * geometry still shows, and say so once. */
        static int s_told;
        if (!s_told) { s_told = 1; SH_DBG("[GPU] texture %dx%d exceeds %d, using white",
                                          w, h, GPU_TEX_MAX); }
        s_curTex = s_white;
        return;
    }

    {   /* The scratch surface is GPU_TEX_MAX wide, so copy row by row rather
         * than in one memcpy -- the source is tightly packed at w, the
         * destination is not. */
        unsigned* dst = (unsigned*)Xe_Surface_LockRect(s_xe, s_tex, 0, 0, w, h, XE_LOCK_WRITE);
        if (dst) {
            const unsigned* src = (const unsigned*)addr;
            int   pitch = s_tex->wpitch / 4;
            int   y;
            for (y = 0; y < h; y++)
                memcpy(dst + (size_t)y * pitch, src + (size_t)y * w, (size_t)w * 4);
        }
        Xe_Surface_Unlock(s_xe, s_tex);
    }
    /* UVs arrive in TEXELS, and the shader normalises them against the surface's
     * real width -- GPU_TEX_MAX, not w, because that is the surface we sample. */
    s_texScale[0] = 1.0f / (float)GPU_TEX_MAX;
    s_texScale[1] = 1.0f / (float)GPU_TEX_MAX;
    s_curTex = s_tex;
}

void GpuNv2a_BindWhite(void)
{
    if (!s_texAddr && s_curTex == s_white)
        return;
    FlushBatch();
    s_texAddr = NULL;
    s_curTex  = s_white;
    /* A 1x1 white page: any UV lands on the single texel. */
    s_texScale[0] = 0.0f;
    s_texScale[1] = 0.0f;
}

/* psx_vram.c really uses this memory, so it must be a genuine allocation.
 * 128-byte aligned because the GPU will DMA out of these buffers. */
void* GpuNv2a_AllocTexMem(int bytes)
{
    void* p;
    if (bytes <= 0)
        return NULL;
    p = memalign(128, (size_t)bytes);
    if (!p)
        SH_DBG("[GPU] AllocTexMem(%d) FAILED", bytes);
    return p;
}

/* PSX semi-transparency: 0 = off, then ABR 0..3 =
 *   0.5B+0.5F, B+F, B-F, B+0.25F.
 * ABR 2 is a REVERSE-SUBTRACT, not a plain subtract: the PSX computes
 * background minus foreground, so getting the operand order backwards inverts
 * every shadow and smoke effect in the game rather than merely dimming it. */
/* Apply the CURRENT blend mode to the device. Split out of SetBlendMode so the
 * per-frame state invalidate can re-assert it without pretending the mode
 * changed. */
static void ApplyBlendState(void)
{
    if (!s_xe)
        return;

    switch (s_blendMode) {
    case 0:
        Xe_SetBlendControl(s_xe, XE_BLEND_ONE, XE_BLENDOP_ADD, XE_BLEND_ZERO,
                                 XE_BLEND_ONE, XE_BLENDOP_ADD, XE_BLEND_ZERO);
        break;
    /* SHADER CONTRACT for the two fractional modes: libXenon exposes no way to
     * set a blend constant (there is no Xe_SetBlendFactor), so the 0.5 and 0.25
     * weights arrive as SOURCE ALPHA from the pixel shader. FlushBatch sets that
     * alpha constant, so the two are always chosen together. */
    case 1:  /* 0.5*B + 0.5*F */
        Xe_SetBlendControl(s_xe, XE_BLEND_SRCALPHA, XE_BLENDOP_ADD, XE_BLEND_INVSRCALPHA,
                                 XE_BLEND_ONE, XE_BLENDOP_ADD, XE_BLEND_ZERO);
        break;
    case 2:  /* B + F (additive) */
        Xe_SetBlendControl(s_xe, XE_BLEND_ONE, XE_BLENDOP_ADD, XE_BLEND_ONE,
                                 XE_BLEND_ONE, XE_BLENDOP_ADD, XE_BLEND_ZERO);
        break;
    case 3:  /* B - F. REVSUBTRACT is dst - src, which is the PSX's
              * background-minus-foreground. Plain SUBTRACT would invert every
              * shadow and smoke effect rather than merely dimming it. */
        Xe_SetBlendControl(s_xe, XE_BLEND_ONE, XE_BLENDOP_REVSUBTRACT, XE_BLEND_ONE,
                                 XE_BLEND_ONE, XE_BLENDOP_ADD, XE_BLEND_ZERO);
        break;
    case 4:  /* B + 0.25*F -- see the shader contract above. */
        Xe_SetBlendControl(s_xe, XE_BLEND_SRCALPHA, XE_BLENDOP_ADD, XE_BLEND_ONE,
                                 XE_BLEND_ONE, XE_BLENDOP_ADD, XE_BLEND_ZERO);
        break;
    default:
        break;
    }
}

/* Everything the device needs that the game does not re-send every frame. */
static void ApplyRenderState(void)
{
    if (!s_xe)
        return;
    /* Depth comes from the ordering table (painter order), not a Z test. */
    Xe_SetZEnable(s_xe, 0);
    Xe_SetZWrite(s_xe, 0);
    Xe_SetCullMode(s_xe, XE_CULL_NONE);
    ApplyBlendState();

    /* The scissor is in FRAMEBUFFER pixels; the game's rect is in PSX content
     * pixels (640x480). xenos_init(VIDEO_MODE_AUTO) picks the display's mode, so
     * the framebuffer is frequently 1280x720 -- scissoring 0,0..640,480 there
     * would clip everything to the top-left quarter of the screen while looking
     * like "most of the geometry is missing". Scale into framebuffer space. */
    if (s_fb && g_Nv2aContentW > 0 && g_Nv2aContentH > 0) {
        int fx = s_scX * s_fb->width  / g_Nv2aContentW;
        int fy = s_scY * s_fb->height / g_Nv2aContentH;
        int fw = s_scW * s_fb->width  / g_Nv2aContentW;
        int fh = s_scH * s_fb->height / g_Nv2aContentH;
        Xe_SetScissor(s_xe, 1, fx, fy, fx + fw, fy + fh);
    } else {
        Xe_SetScissor(s_xe, 0, 0, 0, 0, 0);   /* no surface yet: do not clip */
    }
}

void GpuNv2a_SetBlendMode(int mode)
{
    if (mode == s_blendMode)
        return;
    FlushBatch();
    s_blendMode = mode;
    s_blendChanges++;
    ApplyBlendState();
}

void GpuNv2a_SetScissor(int x, int y, int w, int h)
{
    if (w <= 0 || h <= 0) {          /* reset to the full content rect */
        x = g_Nv2aContentX; y = 0; w = g_Nv2aContentW; h = g_Nv2aContentH;
    }
    if (x == s_scX && y == s_scY && w == s_scW && h == s_scH)
        return;
    FlushBatch();
    s_scX = x; s_scY = y; s_scW = w; s_scH = h;
    s_scissorChanges++;
    /* Through ApplyRenderState, not Xe_SetScissor directly: the content-pixel ->
     * framebuffer-pixel scaling lives there and must not exist in two places. */
    ApplyRenderState();
}

/* Readback needs a resolved copy of the framebuffer, which the count-only path
 * has no way to produce. Reporting NULL makes callers draw the scene live
 * instead of blitting a buffer that was never filled, which would show as a
 * black pane rather than a missing effect. */
const void* GpuNv2a_ReadbackSurface(int fromLastQueued, int* w, int* h, int* pitchBytes)
{
    (void)fromLastQueued;
    if (w) *w = 0;
    if (h) *h = 0;
    if (pitchBytes) *pitchBytes = 0;
    if (!s_warned) {
        s_warned = 1;
        SH_DBG("[GPU] ReadbackSurface unavailable (no resolve target yet)");
    }
    return NULL;
}

int GpuNv2a_Ms(void) { return 0; }

/* The GpuXbox_Fb* entry points are NOT defined here: gpu_xbox.c owns them (it
 * holds the draw/display envs and the screen transform), and it is compiled into
 * this build unchanged. */

void GpuNv2a_DrainGpu(void)
{
    FlushBatch();
    if (s_xe)
        Xe_Sync(s_xe);
}

void GpuNv2a_SetDepthWrite(int enable)
{
    FlushBatch();
    if (s_xe)
        Xe_SetZWrite(s_xe, enable ? 1 : 0);
}

void GpuNv2a_SetPaletteDmaVariant(int variant) { (void)variant; }

/* Freeze-frame capture (pause/save backgrounds). 0 = "no frame captured", so
 * callers fall back to drawing the scene live instead of blitting a buffer that
 * was never filled. */
int  GpuNv2a_FreezeCapture(void) { return 0; }
void GpuNv2a_FreezeBlit(void)    { }
void GpuNv2a_FreezeRelease(void) { }
