#!/usr/bin/env python3
"""Bake the compiled Xenos shaders into a C source file.

They are under a kilobyte together, and making them a separate deployment step
cost two hardware test runs to "shaders not found" -- which is a bad trade for
flexibility nobody asked for. Embedded, the renderer cannot fail to find them.

An on-disk vs.vsu / ps.psu beside the disc image still WINS if present, so
iterating on shaders does not need an ELF rebuild.

    python3 xbox360_port/tools/embed_shaders.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PORT = os.path.dirname(HERE)
SRC = os.path.join(PORT, "shaders")
OUT = os.path.join(PORT, "src", "shaders_embedded.c")


def emit(f, name, path):
    data = open(path, "rb").read()
    if len(data) < 4 or data[0] != 0x10 or data[1] != 0x2A:
        sys.exit("%s: magic is %02x%02x, expected 102a -- libXenon would Xe_Fatal on it"
                 % (path, data[0], data[1]))
    # NOT const. Xe_ShaderApplyVFetchPatches rewrites the vertex-fetch
    # instructions IN PLACE, so a .rodata array would fault on the first
    # instantiation. 128-byte aligned because Xe_LoadShaderFromMemory hands
    # these addresses straight to the GPU.
    f.write("unsigned char %s[%d] __attribute__((aligned(128))) = {\n" % (name, len(data)))
    for i in range(0, len(data), 12):
        f.write("    " + " ".join("0x%02x," % b for b in data[i:i + 12]) + "\n")
    f.write("};\n")
    f.write("const unsigned int %s_len = %d;\n\n" % (name, len(data)))
    return len(data)


def main():
    vs = os.path.join(SRC, "vs.vsu")
    ps = os.path.join(SRC, "ps.psu")
    for p in (vs, ps):
        if not os.path.exists(p):
            sys.exit("missing %s -- run build_shaders.ps1 first" % p)

    with open(OUT, "w", newline="\n") as f:
        f.write("/* SPDX-License-Identifier: GPL-3.0-or-later */\n")
        f.write("/* GENERATED by xbox360_port/tools/embed_shaders.py -- do not edit.\n")
        f.write(" * Source: xbox360_port/shaders/{vs.hlsl,ps.hlsl}, compiled with the\n")
        f.write(" * Xbox 360 XDK's fxc. Regenerate with build_shaders.ps1 then this script. */\n\n")
        n1 = emit(f, "g_ShaderVsEmbedded", vs)
        n2 = emit(f, "g_ShaderPsEmbedded", ps)

    print("wrote %s  (vs=%d bytes, ps=%d bytes)" % (OUT, n1, n2))


if __name__ == "__main__":
    main()
